sudo: required
language: generic
services:
  - docker
before_install:
  - docker build -t snly2386/testapp:latest -f Dockerfile.dev .
script:
  - docker run -e CI=true snly2386/testapp npm run test -- --coverage